apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 3
  template:
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "devopsjourney1/mywebapp:latest"
        ports:
        - containerPort: 80